// <auto-generated />
using System;
using Data.DbCotext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MatchCombateContext))]
    partial class MatchCombateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Domain.Model.Fight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Box")
                        .HasMaxLength(23)
                        .HasColumnType("varchar(23)")
                        .HasColumnName("Octogono");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Local");

                    b.HasKey("Id");

                    b.ToTable("Lutas");
                });

            modelBuilder.Entity("Domain.Model.Fighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Cpf");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Criado_em");

                    b.Property<int?>("FightId")
                        .HasColumnType("int")
                        .HasColumnName("LutaId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Nome");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Apelido");

                    b.Property<int>("WeightClass")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Peso");

                    b.HasKey("Id");

                    b.HasIndex("FightId");

                    b.ToTable("Lutador");
                });

            modelBuilder.Entity("Domain.Model.Fighter", b =>
                {
                    b.HasOne("Domain.Model.Fight", "Fight")
                        .WithMany("Fighters")
                        .HasForeignKey("FightId");

                    b.Navigation("Fight");
                });

            modelBuilder.Entity("Domain.Model.Fight", b =>
                {
                    b.Navigation("Fighters");
                });
#pragma warning restore 612, 618
        }
    }
}
